server:
  port: 8080
spring:
  application:
    name: kurly

---

# local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kulry?dontTrackOpenResources=true&serverTimezone=Asia/Seoul
    username: koot
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
