server:
  port: 8000
spring:
  application:
    name: kurly
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.37.92.138:3306/kurly?dontTrackOpenResources=true&serverTimezone=Asia/Seoul
    username: admin
    password: kurly1234

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate.format_sql: true
    database: mysql
